name: Download And Save

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Download
        run: |
          mkdir data
          cd data
          gdown "https://drive.google.com/uc?id=1IDJyqTIgRpIiIPmiVRuEtNh6msuUQKwr"

      - name: Move into repo
        run: |
          mkdir -p downloads
          mv data/* downloads/

      - name: Commit to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add downloads/
          git commit -m "Add downloaded file"
          git push
