name: Download and Release File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Download file
        run: |
          mkdir data
          cd data
          gdown "https://drive.google.com/uc?id=1IzEABxNRQtqYVo9I88e_47gF2eyXIpAZ"

      - name: Move file to workspace
        run: |
          mkdir release_files
          mv data/* release_files/

      - name: Create Git tag
        run: |
          git tag v2
          git push origin v2

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2
          name: "Auto Release v2
          files: release_files/*
