name: Download and Release File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Download file
        run: |
          mkdir data
          cd data
          gdown "https://drive.google.com/uc?id=1RXeFCO0cDp_CbrJT93tzuM0bkXdWjgjs"

      - name: Move file to workspace
        run: |
          mkdir release_files
          mv data/* release_files/

      - name: Create Git tag
        run: |
          git tag v3
          git push origin v3

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v3
          name: "Auto Release v3"
          files: release_files/*
